# Generated by Django 3.1.2 on 2020-10-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentimg',
            old_name='image',
            new_name='content_img_choice',
        ),
    ]
